### ISSUE TITLE
Is it possible to compile Linux based applications using android-ndk-rs?

### ISSUE THREAD

**Issue by Joe23232** [rust-windowing/android-ndk-rs#177]
There is an application called [Termux](https://termux.com/) that allows you to run Linux terminal based applications on it such as `htop` etc (probably I would have to recompile it to get it to work on ARM).

So using the `android-ndk-rs` crate, does it offer something similar to `termux` so that I can easily port any of my Rust programed Linux applications to Android?

**Comment by MarijnS95** [comment]
The `android-ndk-rs` crate, and in particular `cargo apk` help cross-compiling native libraries and binaries with the toolchain from the Android NDK, that are subsequently packaged in an APK. The resulting binaries (obviously) run on the device as well as inside Termux, but the main goal is to create APKs that use Androids `NativeActivity` to show an activity on screen, not terminal applications.

There are issues around where users successfully use `cargo apk check`/`cargo apk build` to build just the native binaries, and manually copy them out of `target/<arch>-linux-android/debug/<your executable>` to the device. [`cargo-ndk`](https://crates.io/crates/cargo-ndk) exists too, and solely compiles Rust crates to Android-targeted binaries using the NDK, but without providing the additional steps and tooling to package APKs, using the NDK and creating native activities. It is a bit unfortunate that these tools (their code-base) isn't unified as they achieve the exact same goal up until that point.

Note that Termux provides a Linux (Ubuntu/Debian based) environment with lots of common packages to perform tasks on UNIX and develop applications. In that sense it has very different goals than `android-ndk-rs` and can in no way be called "similar", but together they form a very powerful combination. Here's what you can do:

- Install `rust` inside Termux and compile, develop and run your applications on-device directly!
- Use `cargo-ndk` or `cargo-apk` to cross-compile your applications from a PC to run on an Android device. Deploy the resulting binaries to your device and use them from a terminal emulator like Termux.

In order to fully answer your question, I need one bit more information: what kind of "Rust programed Linux applications" are we talking about (console/REPL only?), and where do you intend to run them (directly on the device via eg. an `adb shell`, started from a Java application using `System.exec`, or from a terminal emulator like Termux)?

**Comment by Joe23232** [comment]
@MarijnS95 Just a question what is the difference between `android-ndk-rs` vs `cargo-apk` vs `cargo-ndk`? I understand you explained to me how `cargo-ndk` works but how does it compare to the other two?

> The resulting binaries (obviously) run on the device as well as inside Termux,

So if it is a terminal based application (something like `htop` for example), then can I get it to run without Termux, even if it does not show an output?

> but the main goal is to create APKs that use Androids NativeActivity to show an activity on screen, not terminal applications.

So say if I made another `htop`, it would obviously work on Termux, but would it also work on NativeAcitivty, is NativeActivity an alternative to Termux?

**Comment by MarijnS95** [comment]
@Joe23232 Before answering your questions, take some time to familiarize yourself with the following information, readily available:

- See the available crates provided by this repository, `android-ndk-rs`, by looking at the README. All crates have their own REAMDE too, explaining what they are for;
- Termux is an _app_ that provides a terminal emulator (a way to type and see the output of commands directly on the screen of your phone), and at the same time provides the Linux environment to make it usable because the environment on your phone (reminder: Android runs a Linux kernel too) is pretty bare-bones.
  You [linked their home-page](https://termux.com/). Please read it, as it explains exactly what it does and what to use it for;
- `NativeActivity` is a special way to write Android apps fully in native code, no Java required. It is usually used for games, and you'll have to perform all drawing yourself.
  https://developer.android.com/ndk/guides/concepts#naa

**Comment by dvc94ch** [comment]
My guess is that alacrity could be built with cargo-apk and you could somehow get something to work. Doing unsupported things is interesting, but it means you're on your own.

**Comment by Joe23232** [comment]
I see thanks guys.

**Comment by dvc94ch** [comment]
People have gotten iced to work on Android. Would be exciting to get support upstream, working out the quirks and adding an example to android-ndk-rs.

**Comment by Joe23232** [comment]
@dvc94ch DId they have to do some hacky way to get it to work or it just worked?

**Comment by dvc94ch** [comment]
https://github.com/hecrj/iced/issues/891
https://github.com/hecrj/iced/issues/302

**Comment by Joe23232** [comment]
cool thanks
