### ISSUE TITLE
Does it support web based application(s)?

### ISSUE THREAD

**Issue by Raj2032** [rust-windowing/android-ndk-rs#210]
Hi there, there are some GUI libraries such as [iced](https://github.com/iced-rs/iced) and [rocket](https://rocket.rs/) which allows me to design web applications but does not support developing GUI Android applications at all.

I know that Android has webview. Using one of your tools (such as `cargo-apk` etc) am I able to easily port the web application to Android?

**Comment by 707090** [comment]
The ndk_glue crate is a Rust implementation/layer over the Android [NativeActivity class](https://developer.android.com/reference/android/app/NativeActivity) ([android usage sample](https://github.com/android/ndk-samples/tree/master/native-activity)). This class provides an Activity with bindings to a set up C++ classes with callbacks for things like input events and window/graphics surface events. Because the use cases for NativeActivity (and thus the ndk_glue crate) are for targeting typically graphics rendering applications like games, this crate wouldnt meet a web porting use case.

However, porting to a super simple android app with a single web view should be pretty easy besides. If you want to port a web app to Android by just leaving it as a web app (and writing whatever custom HTML/CSS/JS for when it is mobile) and using a web view, you can simply make a basic app with Android Studio, use the "fullscreen app" template, and simply add a web view which fills the full screen. (This would be a normal Java solution and not involve Rust)

[How to use a web view](https://developer.android.com/guide/webapps/webview)
[Basics for building first app with Android Studio](https://developer.android.com/codelabs/build-your-first-android-app#0)

**Comment by dvc94ch** [comment]
Great answer, thanks @707090
