### ISSUE TITLE
proper logging tutorial?

### ISSUE THREAD

**Issue by lattice0** [rust-windowing/android-ndk-rs#281]
All my functions are called by Java, so I cannot do something like

```
#[cfg_attr(
    target_os = "android",
    ndk_glue::main(backtrace = "on", logger(level = "debug", tag = "hello-world"))
)]
fn main() {
}
```

and I also cannot put this on

```
#[no_mangle]
pub extern "system" fn Java_com_example_myFunction
```

and also I cannot call a normal function from this function above because I need to pass arguments and this `cfg_attr` does not accept arguments. Is there a way to activate loggin on a `pub extern "system" fn Java_com_example_myFunction` function?

**Comment by MarijnS95** [comment]
I think that's what https://docs.rs/android_logger/latest/android_logger/ exists for.

**Comment by lattice0** [comment]
@MarijnS95 found this on google but didn't want to add a new crate just for that. So it looks like android-ndk-rs can't do logging? The logging attribute is just a convenience? I needed debug development logging, not professional log. Couldn't this cfg attribute work for extern system functions too?

**Comment by MarijnS95** [comment]
> So it looks like android-ndk-rs can't do logging?

The `ndk-glue` repo provides a function for this to direct directly to Android system logs:

https://github.com/rust-windowing/android-ndk-rs/blob/be552638ad0e7ce51b7683bbe6a430396e691157/ndk-glue/src/lib.rs#L36-L47

You can call this from `ndk_sys` too, but perhaps we should remove this clean(er) wrapper into the `ndk` for generic usage.

> The logging attribute is just a convenience? [...] Couldn't this cfg attribute work for extern system functions too?

The attribute ties into the `ndk-glue` system which as you said is not applicable to random functions... _at all_... This emits all the necessary intialization logic specifically for a `NativeActivity` app:

https://github.com/rust-windowing/android-ndk-rs/blob/197d491faa0623c8b2e24f7113809acd32037cf7/ndk-macro/src/expand.rs#L49-L52

> I needed debug development logging, not professional log.

Just stdout and stderr, from `(e)println!` and `dbg!`? That's forwarded to the `android_log()` function above:

https://github.com/rust-windowing/android-ndk-rs/blob/be552638ad0e7ce51b7683bbe6a430396e691157/ndk-glue/src/lib.rs#L172-L191

Otherwise we should just move `android_log()` to the NDK so that you can call it manually there, but then you're going directly against Rust's standard logging system (https://github.com/rust-lang/log).

**Comment by lattice0** [comment]
Thanks, this logging you pasted is already enough for testing
