### ISSUE TITLE
Replace `hardware_buffer` and `trace` features with their respective `api-level-23/26`

### ISSUE THREAD

**Issue by MarijnS95** [rust-windowing/android-ndk-rs#318]
Features thus far seem to be used specifically in `ndk-sys` to prevent linking against additional libraries, for content that is provided outside of `libandroid.so`:

https://github.com/rust-windowing/android-ndk-rs/blob/d104d01f116b537babdc94d8c9889581f8d63a02/ndk-sys/src/lib.rs#L43-L53

However, `hardware_buffer` and `trace` have their content available directly in `libandroid.so` - making these features only guard Rust code, in my eyes unnecessarily. It seems much more clear to enable everything `libandroid.so` has to offer solely when a certain API level is turned on. After all, we don't replicate this feature guarding pattern for other "subsystems" of the Android API, only for tracing and hardware_buffer.

@JasperDeSutter What's your thought on this?

**Comment by JasperDeSutter** [comment]
To me it makes the most sense to do everything the same way, and I guess we don't want to add a bunch more features for the other parts of the ndk 😄
I agree we should remove these two, and replace them by api-level feature guards in the code. It will also be useful for me since I almost always have to enable them!

I don't know what the best approach is to deprecating features, adding them to default features and keeping around dummy versions for one minor version? Otherwise we'll have Cargo complaining about these features not existing in dependent crates.

**Comment by MarijnS95** [comment]
@JasperDeSutter Thanks for confirming, I'll get right on it!

> I don't know what the best approach is to deprecating features, adding them to default features and keeping around dummy versions for one minor version? Otherwise we'll have Cargo complaining about these features not existing in dependent crates.

The next release is going to be one big, breaking one. I think it's fine to also tackle this at once and just remove them altogether - there's no `#[deprecated]` flag for features after all (but we could mimic something like that). As long as it's in the changelog :grimacing:
