### ISSUE TITLE
error: failed to verify the checksum of `ndk-sys v0.4.0`

### ISSUE THREAD

**Issue by Fuuzetsu** [rust-windowing/android-ndk-rs#368]
I suspect it's because of https://github.com/rust-lang/cargo/issues/7180

linked to upload to crates.io from couple of hours ago

![w](https://user-images.githubusercontent.com/893115/203178358-952a0f0c-50be-4232-8cbe-d5ce329a8c3a.png)

I guess maybe it's best to refrain from uploading such versions and instead doing 0.4.1, 0.4.2 and so on...

**Comment by MarijnS95** [comment]
I suspect that's because of bad CI tuning: publishes should only happen on pushes to _TAGS_, but it seems we run it on `master` so it published the result of #324 before we bumped the version and made a formal release.

I've yanked the offending version that should not have been released ~apologies~ _blame our CI_ for the inconvenience.
