### ISSUE TITLE
`cargo apk -- build --release` doesn't build in `release` profile anymore

### ISSUE THREAD

**Issue by torokati44** [rust-windowing/android-ndk-rs#375]
I'm trying to use `cargo-apk` to only build a shared library from Rust which then I'll load and use from a "regular" (Java+Kotlin) Android project - so I don't need any APK generation, code signing, etc. from `cargo-apk`.

I was using `cargo apk -- build --release` for this, as suggested here: https://github.com/rust-windowing/android-ndk-rs/issues/326#issuecomment-1214638774

This used to work well, however, since then, it has stopped building in `release` mode for some reason, as can be seen here:
https://github.com/torokati44/ruffle-android/actions/runs/3623790481/jobs/6110051919

![image](https://user-images.githubusercontent.com/288816/206160191-732282b4-1563-46c7-899e-07936eb04a94.png)

![image](https://user-images.githubusercontent.com/288816/206160289-47bff483-d101-4382-aaf7-267308e1c0e8.png)

**Comment by torokati44** [comment]
Perhaps this was caused by https://github.com/rust-windowing/android-ndk-rs/pull/363.

**Comment by MarijnS95** [comment]
This is specifically caused by https://github.com/rust-windowing/android-ndk-rs/pull/363/commits/e2b9db4235138ee7e24d2c57c797a6c85698e0b2 as `args.update_from_arg_matches(&m).unwrap();` is setting `Args::release` back to `false` if `--release` wasn't present in the new args.

I'll investigate if this is intended, if there's a way around it, or if I should just revert that specific commit.

**Comment by torokati44** [comment]
Thank you for the quick fix, now it works just as well as before!
